########################################################################
# prjone/config/Makefile
# $Id$
########################################################################

SHELL=/bin/sh
PLAT=$(shell uname -s) 

all:

install:
	cp -f makefile_rules.$(PLAT) makefile_rules

clean:

uninstall:
	rm -f makefile_rules

########################################################################
